# -*- coding: utf-8 -*-
"""no fixed FinalQuantumDaysSimulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDTJC9JT6tkL6ZgsCqipR_N1ylTXPQXf

Big Picture:

1. Simulate a Fixed Eta Case, Find The Power Ramp From That Simulation

2. Using That Power Ramp; simulate the modulating case for direct comparison.
"""

#Importing + Defining constants for both simulations

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
from scipy import constants

#Fixed parameters

a_0 = constants.physical_constants['Bohr radius'][0]
a = 98*a_0 #m, s-wave scattering length for Rb87
m = 1.44316060e-25 #kg, atomic mass of Rb87 https://steck.us/alkalidata/rubidium87numbers.1.6.pdf
kBoltz = constants.Boltzmann #m^2 kg s^-2 K^-1, Boltzmann's constant

wavelength = 1064*10**-9 #m laser wavelength
h = 6.62607015 * 10**-34
cLight = 2.99792458E+08
taulife = 26.2348E-9
naturallinewidth = 1/(2*np.pi*taulife)
I_sat = 25.03 #W/m^2 #from https://steck.us/alkalidata/rubidium87numbers.1.6.pdf
detuning = cLight/wavelength - cLight/780e-9
E_r =(h**2/wavelength**2)/(2*m) #recoil energy, J


K_3 = 4.3e-29 * 10**-12  #Three body coefficient Olson et. al for Rb87 s-wave https://arxiv.org/abs/1211.3469


alpha_si = h*0.0794e-4 # Hzm^2/V Atomic polarizability of Rb87 https://steck.us/alkalidata/rubidium87numbers.1.6.pdf
mu0	= 2E-7*2*np.pi						# Permeability of vacuum (N/A^2)
epsilon0	= 1/(mu0*cLight**2)		## Permittivity of vacuum (F/m)

Gamma_bg = 1.7/100  # s^-1 This rate

g = 9.81 #m/s^2

#Three constants defined for clarity

C_1 = (8*a**2*m)/(np.pi*kBoltz) #associated with elastic collisions
C_2 = E_r/(3*kBoltz) #associated with spontaneous scattering
C_3 = (K_3*m**3)/(24*np.sqrt(3)*np.pi**3*kBoltz**3) #associated with 3-body loss
C_4 = 2*alpha_si/(epsilon0*cLight*np.pi) #Trap depth constant factor


t_span = (0, 1)  # Time range in seconds
t_eval = np.linspace(*t_span, 1000)

Waist_2_factor = 1
W_1 = 42*10**-6 #unmodulated waist from Chayse's data
zRayleigh_1 = np.pi*W_1**2/wavelength
W_2 = Waist_2_factor*W_1
zRayleigh_2 = np.pi*W_2**2/wavelength
f = (1 / W_1**2) / (1 / W_1**2 + 1 / W_2**2) #Power splitting fraction to each laser

def P_exp(t, P_0, Tau_P):
    return P_0*np.exp(-t/Tau_P) #assuming exponential ramp

def Pdot_exp(t, P_0, Tau_P):
    return -P_0/Tau_P*np.exp(-t/Tau_P) #assuming exponential ramp

P_1_exp = P_exp(t_eval, 5, 1)
P_2_exp = P_exp(t_eval, 5, 1)
Pdot_1_exp = Pdot_exp(t_eval, 5, 1)
Pdot_2_exp = Pdot_exp(t_eval, 5, 1)
U_1_exp = C_4*P_1_exp/W_1**2 #unmodulated trap depth from first laser
U_2_exp = C_4*P_2_exp/W_2**2 #unmodulated trap depth from second laser
U_center_exp = (U_1_exp+U_2_exp) #center trap depth
I_center_exp = 2*U_center_exp/alpha_si #center intensity

#This is the first simulation, fixed eta, the goal of this is to find the Power Ramp which we will use to compare

def equations(t, y, P_ramp, t_eval):
    N, T = y
    idx = np.searchsorted(t_eval, t, side='right') - 1
    P = 2*float(P_ramp[idx])
    U_center = C_4 * P / W_1**2
    I_center = 2*U_center/alpha_si
    U_1 = f*U_center
    U_2 = (1-f)*U_center
    U_1_array = C_4*(P_ramp)/W_1**2
    U_2_array = C_4*(P_ramp)/W_2**2
    U_dot_1_list = C_4*Pdot_exp(t_eval, 5, 1)/W_1**2
    U_dot_2_list = C_4*Pdot_exp(t_eval, 5, 1)/W_2**2
    U_dot_1_list.tolist()
    U_dot_2_list.tolist()

    U_1 = C_4*(P)/W_1**2
    U_2 = C_4*(P)/W_2**2

    U_dot_1 = float(U_dot_1_list[idx])#one at a time
    U_dot_2 = float(U_dot_2_list[idx])

    U_center = U_1 + U_2
    I_center = 2 * U_center / alpha_si

    omega_x = np.sqrt((4/m)*(U_1/W_1**2+U_2/W_2**2))
    omega_y = np.sqrt((1/m)*(4*U_1/W_1**2+2*U_2/zRayleigh_2**2))
    omega_z = np.sqrt((1/m)*(4*U_2/W_2**2+2*U_1/zRayleigh_1**2))
    omegaxyz = omega_x*omega_y*omega_z
    omega_bar = (omegaxyz)**(1/3)

    omega_dot_x = (1/(2*omega_x)) * (4/m) * (U_dot_1/W_1**2 + U_dot_2/W_2**2)
    omega_dot_y = (1/(2*omega_y)) * (1/m) * (4*U_dot_1/W_1**2 + 2*U_dot_2/zRayleigh_2**2)
    omega_dot_z = (1/(2*omega_z)) * (1/m) * (4*U_dot_2/W_2**2 + 2*U_dot_1/zRayleigh_1**2)

    omega_dot_bar_over_omega_bar = (omega_dot_x/omega_x + omega_dot_y/omega_y + omega_dot_z/omega_z) / 3

    gamma_ev = C_1*((U_center/(kBoltz*T))-4)*np.exp(-(U_center/(kBoltz*T)))*omegaxyz*(N/T)
    gamma_3b = C_3*omegaxyz*(N**2/T**3)
    gamma_bg = Gamma_bg
    gamma_sc = (naturallinewidth/2)* (I_center/I_sat)/ (1+(I_center/I_sat)+4*(detuning/naturallinewidth)**2)
    temp_scale_factor = (U_center/(kBoltz*T) + (U_center/(kBoltz*T)-5)/(U_center/(kBoltz*T) - 4) -3)

    dN_dt = - (gamma_ev + gamma_3b + gamma_bg) * N

    dT_dt = -((gamma_ev/3) * temp_scale_factor - (gamma_3b/3)) * T + gamma_sc * C_2 + omega_dot_bar_over_omega_bar * T

    return [dN_dt, dT_dt]

P_ramp = P_exp(t_eval, 5, 3)
N0 = 10**7 # Initial atom number one tenth of atoms roughly
T0 = 10*10**-6# Initial temperature, Kelvin
y0 = [N0, T0]
solution_unmodulated = solve_ivp(equations, t_span, y0, args=(P_ramp, t_eval), t_eval=t_eval)
t_sol = solution_unmodulated.t
N_sol_unmodulated = solution_unmodulated.y[0]
T_sol_unmodulated = solution_unmodulated.y[1]

print("After 1 second, N=", N_sol_unmodulated[-1], "atoms")
print("After 1 second, T=", T_sol_unmodulated[-1], "K")
print("Minimum temperature was acheived was", min(T_sol_unmodulated), "K", "at time", t_sol[np.argmin(T_sol_unmodulated)])

def calculate_center_i(T):
    U_center = C_4 * P_ramp / W_1**2
    I_center = 2 * U_center / alpha_si
    return I_center

I_center = calculate_center_i(T_sol_unmodulated)  # Use the correct temperature solution

# Define spatial grid
x = np.linspace(-100e-6, 100e-6, 1000)
y = np.linspace(-100e-6, 100e-6, 1000)
X, Y = np.meshgrid(x, y)

# Compute intensity distributions
I_total_initial = I_center[0] * (np.exp(-2*X**2 / W_1**2) + np.exp(-2*Y**2 / W_2**2))
I_total_final = I_center[-1] * (np.exp(-2*X**2 / W_1**2) + np.exp(-2*Y**2 / W_2**2))

# Plotting Code
fig, axs = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Unmodulated Beam Dynamics ($\eta=5$)', fontsize=16)

# 1. Power Ramp for Unmodulated Beams
axs[0, 0].plot(t_sol, P_ramp, color='#1b9e77')
axs[0, 0].set_title('Power Ramp for Unmodulated Beams')
axs[0, 0].set_xlabel('Time (s)')
axs[0, 0].set_ylabel('Power (W)')
axs[0, 0].grid(True)

# 2. Initial/Final Intensity Profiles
axs[0, 1].plot(x*1e6, I_total_initial[:, len(x)//2], label='Initial')
axs[0, 1].plot(x*1e6, I_total_final[:, len(x)//2], label='Final')
axs[0, 1].set_title('Initial/Final Intensity Profiles')
axs[0, 1].set_xlabel('Position (µm)')
axs[0, 1].set_ylabel('Intensity (W/m²)')
axs[0, 1].grid(True)
axs[0, 1].legend()

# 3. Number of Atoms vs Time (semilogy)
axs[1, 0].semilogy(t_sol, N_sol_unmodulated, color='#e7298a')
axs[1, 0].set_title('Number of Atoms vs Time')
axs[1, 0].set_xlabel('Time (s)')
axs[1, 0].set_ylabel('Number of Atoms')
axs[1, 0].grid(True)

# 4. Trap Temperature vs Time
axs[1, 1].plot(t_sol, T_sol_unmodulated*10**6, color='#66a61e')
axs[1, 1].set_title('Trap Temperature vs Time')
axs[1, 1].set_xlabel('Time (s)')
axs[1, 1].set_ylabel('Temperature (µK)')
axs[1, 1].grid(True)

# Adjust layout
plt.show()

#Second Simulation

def equations(t, y, P_ramp, t_eval):
  N, T = y

  idx = np.searchsorted(t_eval, t, side='right') - 1
  P = float(P_ramp[idx])

  h0_x = W_1/10   # modulation amplitude (m)
  h0_y = W_1/10   # modulation amplitude (m)
  def f_U(h0, w0): #at the center, modulation follows
      return (3 * np.pi * w0**2) / (8 * h0)

  U_1_array = C_4*(P_ramp)*(f_U(h0_x, W_1)/W_1**2)
  U_2_array = C_4*(P_ramp)*(f_U(h0_y, W_2)/W_2**2)
  U_dot_1_list = np.array(np.gradient(U_1_array)) #New terms, numerical derivatives of U_1 and U_2
  U_dot_2_list = np.array(np.gradient(U_2_array))
  U_dot_1_list.tolist()
  U_dot_2_list.tolist()

  U_1 = C_4*(P)*(f_U(h0_x, W_1)/W_1**2)
  U_2 = C_4*(P)*(f_U(h0_y, W_2)/W_2**2)

  U_dot_1 = float(U_dot_1_list[idx])#one at a time
  U_dot_2 = float(U_dot_2_list[idx])

  U_center = U_1 + U_2
  I_center = 2 * U_center / alpha_si

  omega_x = np.sqrt((4/m)*(U_1/W_1**2+U_2/W_2**2))
  omega_y = np.sqrt((1/m)*(4*U_1/W_1**2+2*U_2/zRayleigh_2**2))
  omega_z = np.sqrt((1/m)*(4*U_2/W_2**2+2*U_1/zRayleigh_1**2))
  omegaxyz = omega_x*omega_y*omega_z
  omega_bar = (omegaxyz)**(1/3)

  omega_dot_x = (1/(2*omega_x)) * (4/m) * (U_dot_1/W_1**2 + U_dot_2/W_2**2)
  omega_dot_y = (1/(2*omega_y)) * (1/m) * (4*U_dot_1/W_1**2 + 2*U_dot_2/zRayleigh_2**2)
  omega_dot_z = (1/(2*omega_z)) * (1/m) * (4*U_dot_2/W_2**2 + 2*U_dot_1/zRayleigh_1**2)

  omega_dot_bar_over_omega_bar = (omega_dot_x/omega_x + omega_dot_y/omega_y + omega_dot_z/omega_z) / 3

  gamma_ev = C_1*((U_center/(kBoltz*T))-4)*np.exp(-(U_center/(kBoltz*T)))*omegaxyz*(N/T)
  gamma_3b = C_3*omegaxyz*(N**2/T**3)
  gamma_bg = Gamma_bg
  gamma_sc = (naturallinewidth/2)* (I_center/I_sat)/ (1+(I_center/I_sat)+4*(detuning/naturallinewidth)**2)
  temp_scale_factor = (U_center/(kBoltz*T) + (kBoltz*T-5)/(kBoltz*T-4) -3)

  dN_dt = - (gamma_ev + gamma_3b + gamma_bg) * N

  dT_dt = -((gamma_ev/3) * temp_scale_factor - (gamma_3b/3)) * T + gamma_sc * C_2 + omega_dot_bar_over_omega_bar * T

  return [dN_dt, dT_dt]

y0 = [N0, T0]
modsol = solve_ivp(equations, t_span, y0, args=(P_ramp, t_eval), t_eval=t_eval)
t_sol = modsol.t
N_sol_mod = modsol.y[0]
T_sol_mod = modsol.y[1]

print("After 1 second, N=", N_sol_mod[-1], "atoms")
print("After 1 second, T=", T_sol_mod[-1], "K")
print("Minimum temperature was acheived was", min(T_sol_mod), "K", "at time", t_sol[np.argmin(T_sol_mod)])

print(N_sol_mod[0], N_sol_unmodulated[0])

# Compute Intensity Distributions for Modulated Case
h0_x = W_1/8   # modulation amplitude (m)
h0_y = W_1/8  # modulation amplitude (m)

def f_U(h0, w0): #at the center, modulation follows
    return (3 * np.pi * w0**2) / (8 * h0)

def calculate_center_i(T):
    I_center = 2 * U_center / alpha_si
    return I_center

# Modulated U_center
U_1_mod = C_4*(P_exp(t_eval, 5, 1))*(f_U(h0_x, W_1)/W_1**2)
U_2_mod = C_4*(P_exp(t_eval, 5, 1))*(f_U(h0_y, W_2)/W_2**2)
U_center_mod = U_1_mod + U_2_mod
I_center_mod = 2 * U_center_mod / alpha_si

# Compute intensity distributions for modulated case
I_total_initial_mod = I_center_mod[0] * (np.exp(-2*X**2 / W_1**2) + np.exp(-2*Y**2 / W_2**2))
I_total_final_mod = I_center_mod[-1] * (np.exp(-2*X**2 / W_1**2) + np.exp(-2*Y**2 / W_2**2))

# Define colorblind-friendly color palette
colors = ['#0072B2', '#D55E00', '#009E73', '#CC79A7']

fig, axs = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Modulated With Painted Potentials Using The Same Power Ramp as Before', fontsize=16)

# 1. Power Ramp for Modulated Beams
axs[0, 0].plot(t_sol, P_ramp, color=colors[0], label='Power Ramp')
axs[0, 0].set_title('Power Ramp for Modulated Beams')
axs[0, 0].set_xlabel('Time (s)')
axs[0, 0].set_ylabel('Power (W)')
axs[0, 0].grid(True)
axs[0, 0].legend()

# 2. Initial/Final Intensity Profiles for Modulated Case
axs[0, 1].plot(x*1e6, I_total_initial_mod[int(len(y)/2), :], color=colors[1], label='Initial')
axs[0, 1].plot(x*1e6, I_total_final_mod[int(len(y)/2), :], color=colors[2], label='Final')
axs[0, 1].set_title('Initial/Final Intensity Profiles (Modulated)')
axs[0, 1].set_xlabel('Position (µm)')
axs[0, 1].set_ylabel('Intensity (W/m²)')
axs[0, 1].grid(True)
axs[0, 1].legend()

# 3. Number of Atoms vs Time (semilogy) for Modulated Case
axs[1, 0].semilogy(t_sol, N_sol_mod, color=colors[3], label='Number of Atoms')
axs[1, 0].set_title('Number of Atoms vs Time (Modulated)')
axs[1, 0].set_xlabel('Time (s)')
axs[1, 0].set_ylabel('Number of Atoms')
axs[1, 0].grid(True, which='both')
axs[1, 0].legend()

# 4. Trap Temperature vs Time for Modulated Case
axs[1, 1].plot(t_sol, T_sol_mod*1e6, color=colors[0], label='Trap Temperature')
axs[1, 1].set_title('Trap Temperature vs Time (Modulated)')
axs[1, 1].set_xlabel('Time (s)')
axs[1, 1].set_ylabel('Temperature (µK)')
axs[1, 1].grid(True)
axs[1, 1].legend()

plt.tight_layout(rect=[0, 0, 1, 0.95])  # Adjust layout to fit title
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.plot(t_sol, P_ramp, label='Power Ramp (Unmodulated)')
plt.xlabel('Time (s)')
plt.ylabel('Power (W)')
plt.title('Power Ramp')
plt.grid(True)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
fig, axs = plt.subplots(2, 2, figsize=(12, 8))

axs[0, 0].semilogy(t_sol, N_sol_unmodulated, 'ko')
axs[0, 0].set_title('N_sol_unmodulated vs. time')
axs[0, 0].set_xlabel('Time (s)')
axs[0, 0].set_ylabel('N_sol_unmodulated')
axs[0,0].grid(True)

axs[0, 1].semilogy(t_sol, T_sol_unmodulated)
axs[0, 1].set_title('T_sol_unmodulated vs. time')
axs[0, 1].set_xlabel('Time (s)')
axs[0, 1].set_ylabel('T_sol_unmodulated')
axs[0,1].grid(True)

axs[1, 0].semilogy(t_sol, N_sol_mod, 'ko')
axs[1, 0].set_title('N_sol_mod vs. time')
axs[1, 0].set_xlabel('Time (s)')
axs[1, 0].set_ylabel('N_sol_mod')
axs[1,0].grid(True)

axs[1, 1].semilogy(t_sol, T_sol_mod)
axs[1, 1].set_title('T_sol_mod vs. time')
axs[1, 1].set_xlabel('Time (s)')
axs[1, 1].set_ylabel('T_sol_mod')
axs[1,1].grid(True)

plt.tight_layout()
plt.show()

def f_U(h0, w0): #at the center, modulation follows
    return (3 * np.pi * w0**2) / (8 * h0)

def calculate_center_i(T):
    I_center = 2 * U_center / alpha_si
    return I_center

h0_x = W_1/2
h0_y = W_1/20
U_1_array = C_4*(P_ramp)*(f_U(h0_x, W_1)/W_1**2)
U_2_array = C_4*(P_ramp)*(f_U(h0_y, W_2)/W_2**2)
U_center = U_1_array + U_2_array
I_center = calculate_center_i(T_sol_mod)

# Define spatial grid
x = np.linspace(-200e-6, 200e-6, 1000)
y = np.linspace(-200e-6, 200e-6, 1000)
X, Y = np.meshgrid(x, y)

# Compute intensity distributions
I_total_initial = I_center[0] * (np.exp(-X**2 / W_1**2) + np.exp(-Y**2 / W_2**2))
I_total_final = I_center[-1] * (np.exp(-X**2 / W_1**2) + np.exp(-Y**2 / W_2**2))
#(3*P_ramp[0]/(4))*((h0_x**2 - X**2)/(h0_x**3)*np.heaviside((h0_x-np.abs(X)),0)*((h0_y**2 - Y**2)/(h0_y**3)*np.heaviside(h0_y-np.abs(Y),0)))
#
print(P_ramp[0])
# Create figure and subplots
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Plot initial 2D intensity
im1 = axes[0, 0].pcolormesh(X * 1e6, Y * 1e6, I_total_initial, shading='auto')
axes[0, 0].set_xlabel('x (μm)')
axes[0, 0].set_ylabel('y (μm)')
axes[0, 0].set_aspect('equal', adjustable='box')
axes[0, 0].set_title('Unmodulate Intensity Distribution')
fig.colorbar(im1, ax=axes[0, 0])
axes[0, 0].grid(True)

# Plot final 2D intensity
im2 = axes[0, 1].pcolormesh(X * 1e6, Y * 1e6, I_total_final, shading='auto')
axes[0, 1].set_xlabel('x (μm)')
axes[0, 1].set_ylabel('y (μm)')
axes[0, 1].set_aspect('equal', adjustable='box')
axes[0, 1].set_title('Modulated Intensity Distribution')
fig.colorbar(im2, ax=axes[0, 1])
axes[0, 1].grid(True)

# Plot initial 1D intensity profiles
axes[1, 0].plot(x * 1e6, I_total_initial[:, len(x)//2], 'b-o', label='x-axis')
axes[1, 0].plot(y * 1e6, I_total_initial[len(y)//2, :], 'r--', label='y-axis')
axes[1, 0].set_xlabel('Position (μm)')
axes[1, 0].set_ylabel('Intensity (a.u.)')
axes[1, 0].set_title('Initial Intensity Profiles')
axes[1, 0].legend()
axes[1, 0].grid(True)

# Plot final 1D intensity profiles
axes[1, 1].plot(x * 1e6, I_total_final[:, len(x)//2], 'b-o', label='x-axis')
axes[1, 1].plot(y * 1e6, I_total_final[len(y)//2, :], 'r--', label='y-axis')
axes[1, 1].set_xlabel('Position (μm)')
axes[1, 1].set_ylabel('Intensity (a.u.)')
axes[1, 1].set_title('Final Intensity Profiles')
axes[1, 1].legend()
axes[1, 1].grid(True)

# Adjust layout
plt.tight_layout()
plt.show()